Code refactor

diff --git a/apt-list-packages b/apt-list-packages
--- a/apt-list-packages
+++ b/apt-list-packages
@@ -1,18 +1,15 @@
 #!/usr/bin/env bash
 
-set -Eeuo pipefail
-trap 'echo_error "\e[1mError: program exited with status ${?} at line ${LINENO}"' ERR
+set -Eeu
+trap 'echo "Error: ${SCRIPT} - Function: ${FUNCNAME:-global context} - Line: ${LINENO} - Status: ${?}"' ERR
 
 # Arguments
+# shellcheck disable=SC2155
+readonly SCRIPT=$(basename "${0}")
 readonly URL="${1}"
 readonly DIST="${2}"
 readonly REPO="${3}"
 readonly ARCH="${4:-$(dpkg --print-architecture)}"
-
-echo_error()
-{
-    echo -e "\e[0;31m${*}\e[0m"
-}
 
 main()
 {
diff --git a/dsf b/dsf
--- a/dsf
+++ b/dsf
@@ -1,16 +1,13 @@
 #!/usr/bin/env bash
 
-set -Eeuo pipefail
-trap 'echo_error "\e[1mError: program exited with status ${?} at line ${LINENO}"' ERR
+set -Eeu
+trap 'echo "Error: ${SCRIPT} - Function: ${FUNCNAME:-global context} - Line: ${LINENO} - Status: ${?}"' ERR
 
 # Arguments
+# shellcheck disable=SC2155
+readonly SCRIPT=$(basename "${0}")
 readonly LEFT="${1:-}"
 readonly RIGHT="${2:-}"
-
-echo_error()
-{
-    echo -e "\e[0;31m${*}\e[0m"
-}
 
 main()
 {
diff --git a/findhome b/findhome
--- a/findhome
+++ b/findhome
@@ -1,9 +1,11 @@
 #!/usr/bin/env bash
 
-set -Eeuo pipefail
-trap 'echo_error "\e[1mError: program exited with status ${?} at line ${LINENO}"' ERR
+set -Eeu
+trap 'echo "Error: ${SCRIPT} - Function: ${FUNCNAME:-global context} - Line: ${LINENO} - Status: ${?}"' ERR
 
 # Arguments
+# shellcheck disable=SC2155
+readonly SCRIPT=$(basename "${0}")
 readonly SEARCH="${1}"
 
 # Settings
@@ -11,11 +13,6 @@ readonly BASE_PATH="${HOME}"
 readonly EXCLUDE_PATHS=(
     "${HOME}/dev/docker-data"
 )
-
-echo_error()
-{
-    echo -e "\e[0;31m${*}\e[0m"
-}
 
 main()
 {
diff --git a/gitops b/gitops
--- a/gitops
+++ b/gitops
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 
-set -Eeuo pipefail
-trap 'echo_error "\e[1mError: program exited with status ${?} at line ${LINENO}"' ERR
+set -Eeu
+trap 'echo "Error: ${SCRIPT} - Function: ${FUNCNAME:-global context} - Line: ${LINENO} - Status: ${?}"' ERR
 
 # Arguments
 # shellcheck disable=SC2155
@@ -33,11 +33,6 @@ print_usage()
     echo
 
     exit 1
-}
-
-echo_error()
-{
-    echo -e "\e[0;31m${*}\e[0m"
 }
 
 check_clean()
diff --git a/purge-packages b/purge-packages
--- a/purge-packages
+++ b/purge-packages
@@ -1,11 +1,23 @@
 #!/usr/bin/env bash
 
-# shellcheck disable=SC2046
-sudo apt autoremove --purge $(dpkg -l | grep "^rc" | awk "{print $2}")
+set -Eeu
+trap 'echo "Error: ${SCRIPT} - Function: ${FUNCNAME:-global context} - Line: ${LINENO} - Status: ${?}"' ERR
 
-snap list --all | awk '/disabled/{print $1, $3}' |
-    while read -r SNAP_NAME REVISION; do
-        sudo snap remove "${SNAP_NAME}" --revision="${REVISION}"
-    done
+# Arguments
+# shellcheck disable=SC2155
+readonly SCRIPT=$(basename "${0}")
 
-flatpak uninstall --unused --delete-data --assumeyes
+main()
+{
+    # shellcheck disable=SC2046
+    sudo apt autoremove --purge $(dpkg -l | grep '^rc' | awk '{print $2}')
+
+    snap list --all | awk '/disabled/{print $1, $3}' |
+        while read -r SNAP_NAME REVISION; do
+            sudo snap remove "${SNAP_NAME}" --revision="${REVISION}"
+        done
+
+    flatpak uninstall --unused --delete-data --assumeyes
+}
+
+main
diff --git a/update-tools b/update-tools
--- a/update-tools
+++ b/update-tools
@@ -1,8 +1,12 @@
 #!/usr/bin/env bash
 
-set -Eeuo pipefail
-trap 'echo_error "\e[1mError: program exited with status ${?} at line ${LINENO}"' ERR
+set -Eeu
+trap 'echo "Error: ${SCRIPT} - Function: ${FUNCNAME:-global context} - Line: ${LINENO} - Status: ${?}"' ERR
 trap 'print_report' EXIT
+
+# Arguments
+# shellcheck disable=SC2155
+readonly SCRIPT=$(basename "${0}")
 
 # Settings
 readonly TOOLS_DIR="${HOME}/dev/tools"
@@ -86,9 +90,11 @@ main()
 
     # Install go
     echo "Installing go"
+    # shellcheck disable=SC2155
     readonly GO_VERSION_OLD="$(go version 2> /dev/null | cut -d ' ' -f 3 | sed 's/go//')"
     local -r GO_VERSION_LATEST="$(curl -sSL "https://golang.org/VERSION?m=text")"
     install_targz "https://dl.google.com/go/${GO_VERSION_LATEST}.linux-amd64.tar.gz" "go" "go"
+    # shellcheck disable=SC2155
     readonly GO_VERSION_NEW="$(go version 2> /dev/null | cut -d ' ' -f 3 | sed 's/go//')"
 
     # Report
